---
- hosts: server02_postgres
  become: yes
  become_user: postgres
  gather_facts: no

  tasks:
  - name: enable and start service postgresql and ensure it is not masked
    systemd:
      name: postgresql
      enabled: yes
      masked: no
      state: started

  - name: ensure database is created
    postgresql_db: name={{POSTGRESQL_DB}}

  - name: ensure user has access to database
    postgresql_user: db={{POSTGRESQL_DB}} name={{POSTGRESQL_USER}} password={{POSTGRESQL_PASSWORD}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{POSTGRESQL_USER}} role_attr_flags=NOSUPERUSER,NOCREATEDB

  - name: ensure no other user can access the database
    postgresql_privs: db={{POSTGRESQL_DB}} role=PUBLIC type=database priv=ALL state=absent

- hosts: server02_postgres
  become: yes
  gather_facts: no

  tasks:
  - name: uploading to folder
    copy:
      src: ../files/
      dest: /etc/postgresql/11/main/

  - name: allowing all listen addresses
    lineinfile:
      dest: /etc/postgresql/11/main/postgresql.conf
      regexp: "^listen_addresses"
      line: "listen_addresses = '*'"

- hosts: server02_postgres
  become: yes
  become_user: postgres
  gather_facts: no

  tasks:
  - name: execute schema.sql on database
    postgresql_db:
      name: "{{POSTGRESQL_DB}}"
      state: restore
      target: /etc/postgresql/11/main/schema.sql

  - name: change owner
    postgresql_query:
      query: ALTER TABLE public.votes OWNER TO {{POSTGRESQL_USER}};
      db: "{{POSTGRESQL_DB}}"

- hosts: server02_postgres
  become: yes
  gather_facts: no

  tasks:
  - name: enable and restart service postgresql and ensure it is not masked
    systemd:
      name: postgresql
      enabled: yes
      masked: no
      state: restarted
