---
- hosts: server02_postgres
  become: yes
  become_user: postgres

  tasks:
  - name: Enable and start the PostgreSQL service
    systemd:
      name: postgresql
      enabled: yes
      masked: no
      state: started

  - name: Ensure database is created
    postgresql_db: name={{POSTGRESQL_DB}}

  - name: Ensure user has access to database
    postgresql_user: db={{POSTGRESQL_DB}} name={{POSTGRESQL_USER}} password={{POSTGRESQL_PASSWORD}} priv=ALL

  - name: Ensure user does not have unnecessary privilege
    postgresql_user: name={{POSTGRESQL_USER}} role_attr_flags=NOSUPERUSER,NOCREATEDB

  - name: Ensure no other user can access the database
    postgresql_privs: db={{POSTGRESQL_DB}} role=PUBLIC type=database priv=ALL state=absent

- hosts: server02_postgres
  become: yes
  become_method: sudo

  tasks:
  - name: Uploading required files
    copy:
      src: ../files/
      dest: /etc/postgresql/11/main/

  - name: Allowing all listen addresses
    lineinfile:
      dest: /etc/postgresql/11/main/postgresql.conf
      regexp: "^listen_addresses"
      line: "listen_addresses = '*'"

- hosts: server02_postgres
  become: yes
  become_user: postgres

  tasks:
  - name: Execute schema.sql on database
    postgresql_db:
      name: "{{POSTGRESQL_DB}}"
      state: restore
      target: /etc/postgresql/11/main/schema.sql

  - name: Change database owner
    postgresql_query:
      query: ALTER TABLE public.votes OWNER TO {{POSTGRESQL_USER}};
      db: "{{POSTGRESQL_DB}}"

- hosts: server02_postgres
  become: yes
  become_method: sudo

  tasks:
  - name: Enable and restart the PostgreSQL service
    systemd:
      name: postgresql
      enabled: yes
      masked: no
      state: restarted
