- hosts: server01_redis
  become: yes
  become_method: sudo
  tasks:
  - name: install packages
    apt:
      name: ['redis-server']
      state: present

- hosts: server01_redis
  tasks:
  - name: Copy redis.conf
    copy:
      src: ../files/redis.conf
      dest: /etc/redis/redis.conf
  
  - name: Restart redis-server.service
    systemd:
      name: redis-server.service
      state: restarted
      enabled: yes
      masked: no