---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes

- hosts: server01_redis
  become: yes
  become_method: sudo
  tasks:
  - name: install packages
    apt:
      name: ['redis-server']
      state: present

- hosts: server02_postgres
  become: yes
  gather_facts: no

  - name: ensure packages are installed
    apt:
      name: ['postgresql', 'libpq-dev', 'python-psycopg2']

- hosts: server03_poll
  become: yes
  become_method: sudo
  tasks:
  - name: install packages
    apt:
      name: ['python3', 'python3-pip', 'python3-dev']
      state: present
  - name: Install uwsgi
    pip:
      name: uwsgi
      executable: pip3

- hosts: server04_result
  become: yes
  become_method: sudo
  gather_facts: no

  - name: ensure packages are installed
    apt:
      name: ['npm', 'nodejs']

- hosts: server05_worker
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Install packages
    apt:
      name: ['openjdk-11-jdk', 'maven']
      update_cache: yes